[log]
enabled=false
file=/var/log/homed.log

[mqtt]
host=localhost
port=1883
prefix=homed
names=false

[homeassistant]
enabled=true
prefix=homeassistant
status=homeassistant/status
update=false

[default]
discovery=true
cloud=true

[device]
database=/opt/homed-zigbee/database.json
properties=/opt/homed-zigbee/properties.json
options=/opt/homed-zigbee/options.json
external=/opt/homed-zigbee/external
ota=/opt/homed-zigbee/ota

[gpio]
status=/sys/class/leds/amber:status/brightness

[zigbee]
adapter=znp
port=/dev/ttyS2
baudrate=115200
panid=0x3000
channel=11
power=5
reset=soft
write=true

[security]
key=0x0167ac11b77e5c4b11cd9315a60fafaa

[debug]
port=false
adapter=false
zigbee=false
