[log]
enabled=false
file=/var/log/homedModbus.log

[mqtt]
host=localhost
port=1883
username=mqtt
password=mqtt
prefix=homed
instance=
names=false

[homeassistant]
enabled=false
prefix=homeassistant
status=homeassistant/status

[device]
database=/opt/homed-modbus/database.json

[port-1]
port=/dev/ttyS1
